services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: spo-prca-em 
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: admin2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data: