server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: redis
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    table: flyway_schema_history_auth

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

security:
  max-failed-attempts: ${MAX_FAILED_ATTEMPTS}
  account-lock-duration-minutes: ${ACCOUNT_LOCK_DURATION}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://localhost,http://localhost:5173,http://localhost}

logging:
  level:
    org.springframework.web.cors: DEBUG