name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/spo-prca-em
            git pull origin main
            docker compose up -d --build
            git checkout develop
            git reset --hard origin/main
            git push origin develop --force-with-lease

      - name: Notify success
        run: echo "Deployed successfully"